version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: postgres
      # POSTGRES_USER: postgres
      # POSTGRES_DB: postgres
  back:
  front:
  pbx:
volumes: